//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfidLauncher.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProfidLauncherTexts___Copy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProfidLauncherTexts___Copy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProfidLauncher.Translations.ProfidLauncherTexts - Copy", typeof(ProfidLauncherTexts___Copy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Beenden.
        /// </summary>
        public static string EXIT {
            get {
                return ResourceManager.GetString("EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Extras.
        /// </summary>
        public static string EXTRA {
            get {
                return ResourceManager.GetString("EXTRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Datei.
        /// </summary>
        public static string FILE {
            get {
                return ResourceManager.GetString("FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Hilfe.
        /// </summary>
        public static string HELP {
            get {
                return ResourceManager.GetString("HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Über PROFID Launcher.
        /// </summary>
        public static string HELPABOUT {
            get {
                return ResourceManager.GetString("HELPABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Hilfe anzeigen.
        /// </summary>
        public static string HELPSHOW {
            get {
                return ResourceManager.GetString("HELPSHOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Profid China Shortcut.
        /// </summary>
        public static string PLCHINA {
            get {
                return ResourceManager.GetString("PLCHINA", resourceCulture);
            }
        }
    }
}
