name: Tags
on: 
  workflow_dispatch:

jobs:
  readtags:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show ref
        run: echo ${{ github.ref }}
    
      - name: List Tags
        run: |
            git tag -l
            git describe --tags $(git rev-list --tags --max-count=1)

      - name: GitVersion Setup
        uses: gittools/actions/gitversion/setup@v1.1.1
        with:
          versionSpec: '5.x'
             
      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v1.1.1
        id: version
        with:
            useConfigFile: true
            configFilePath: GitVersion.yml

      - name: usev
        id: usev1
        run: |
            Write-Output ${{ env.semVer }}